### ISSUE TITLE
libfive compile error

### ISSUE THREAD

**Issue by wenzhengchen** [dilevin/DGPCompFab#5]
Hi Dave, 

Following the instructions, I successfully compiled cling and add the path in the system. Next I want to compile A1. However, when I compile A1, it has compile error.

It shows:

In file included from /home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/xtree.hpp:33:0,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree.cpp:20,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree2.cpp:1:
/home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/progress.hpp:61:10: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
     std::atomic_uint64_t counter;
          ^
[ 41%] Building CXX object imgui/CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.o
In file included from /home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/xtree.hpp:33:0,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree.cpp:20,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree3.cpp:1:
/home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/progress.hpp:61:10: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
     std::atomic_uint64_t counter;
          ^
In file included from /home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/xtree.hpp:33:0,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree_pool.cpp:21,
                 from /home/wz/Desktop/csc2521/DGPCompFab/ThirdParty/libfive/libfive/src/render/brep/xtree_pool2.cpp:10:
/home/wz/Desktop/csc2521/DGPCompFab/A1/../ThirdParty/libfive/libfive/include/libfive/render/brep/progress.hpp:61:10: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
     std::atomic_uint64_t counter;

System: Ubuntu 14.04
GCC:  5.4

I am not sure what happens... It seems the head file does not have some declares?

**Comment by dilevin** [comment]
The assignments only build on ubuntu 18.04. 14.04 doesn't have a new enough version of gcc or boost for this to work.

**Comment by wenzhengchen** [comment]
I see. Let me try it on osx. Thank you!

**Comment by dilevin** [comment]
I think this got resolved in the sense that Ubuntu 16.04 is unsupported. I’m closing it now but please re open if you think it’s still a problem.
